apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Application
      name: infrastructure
    patch: |-
      - op: replace
        path: /spec/source/path
        value: k8s/app-of-apps/overlays/hcloud/infra
  
  - target:
      kind: Application
      name: applications
    patch: |-
      - op: replace
        path: /spec/source/path
        value: k8s/app-of-apps/overlays/hcloud/apps