apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: zitadel-backup-store
  namespace: zitadel
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  configuration:
    destinationPath: s3://zitadel-backups
    endpointURL: https://f692b94900d33a4d47c0d10dd5e1339a.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: zitadel-backup-keys
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: zitadel-backup-keys
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 2
    data:
      compression: gzip
