controllers:
  nodePlacement:
    enabled: false
   
    nodeSelector:
      niovial.io/node-purpose: system
    
    tolerations:
      - key: niovial.io/node-purpose
        operator: Equal
        value: system

