controllers:
  nodePlacement:
    enabled: true
   
    nodeSelector:
      node.niovial.io/pool: system
    
    tolerations:
      - key: node.niovial.io/pool
        operator: Equal
        value: system

