controllers:
  nodePlacement:
    enabled: true
   
    nodeSelector:
      node.niovial.io/pool: system
    
    tolerations:
      - key: node.niovial.io/pool
        operator: Equal
        value: system

spegel:
  enabled: false

monitoring:
  storage:
    size:
      metrics: 30Gi