apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/rtnkwami/portfolio-hub.git
    path: k8s/clusters/hetzner
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true