apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.networking.tls.issuer.environment }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: {{ .Values.networking.tls.issuer.email }}
    {{- if eq .Values.networking.tls.issuer.environment "staging" }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- else if eq .Values.networking.tls.issuer.environment "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    {{ fail ("Invalid environment set in networking.tls.issuer.environment. Expected 'staging' or 'production'") }}
    {{- end }}
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.networking.tls.issuer.environment }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: domain-credentials
              key: token