apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter-crds
  namespace: flux-system
spec:
  dependsOn:
    - name: vm-stack
  # interval at which HelmRelease config is reconciled
  interval: 1m
  targetNamespace: kube-system
  upgrade:
    cleanupOnFail: true
  chart:
    spec:
      chart: karpenter-crds
      version: 1.11.1
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
      # interval at which chart source is reconciled
      interval: 2h