genesis:
  controllers:
    nodePlacement:
      nodeSelector:
        node.niovial.io/pool: system
      tolerations:
        - key: node.niovial.io/pool
          operator: Equal
          value: system
  
  spegel:
    enabled: true
  
  secrets:
    provider: infisical
    config:
      infisical:
        hostAPI: https://app.infisical.com
        auth:
          universalAuthCredentials:
            clientId:
              name: infisical-credentials
              key: clientId
              namespace: external-secrets
            clientSecret:
              name: infisical-credentials
              key: clientSecret
              namespace: external-secrets
        secretsScope:
          projectSlug: homelab-43la
          environmentSlug: staging
  
  networking:
    tls:
      issuer:
        email: cert-alerts@niovial.io
        remoteRef: /dns/niovial-io/certmanager-token
    
    dns:
      remoteRef: /dns/niovial-io/externaldns-token
    
    externalGateway:
      infrastructureAnnotations:
        load-balancer.hetzner.cloud/name: "external-gateway"
        load-balancer.hetzner.cloud/location: "nbg1"
    
    tailnet:
      credentials:
        clientId:
          remoteRef: /tailscale/operator-client-id
        clientSecret:
          remoteRef: /tailscale/operator-client-secret

zitadel:
  app:
    domain: iam.niovial.io
  database:
    ha:
      enabled: true
    
    nodeSelector:
      node.niovial.io/pool: database
    
    tolerations:
      - key: node.niovial.io/pool
        operator: Equal
        value: database
    
  secrets:
    provider: infisical
    
    masterkey: /zitadel/master-key
   
    backupKeys:
      accessKeyId: /zitadel/r2-backup-key-id
      accessSecretKey: /zitadel/r2-backup-key
  
  backups:
    version: 2
    store:
      endpointUrl: https://f692b94900d33a4d47c0d10dd5e1339a.r2.cloudflarestorage.com
    bucket: zitadel-backups
    recovery:
      enabled: false