apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: certmanager-cloudflare-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  data:
    - secretKey: token
      remoteRef:
        key: k8s-certmanager-token
