apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: domain-credentials
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: {{ .Values.secrets.provider }}
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.networking.tls.issuer.remoteRef }}
