{{- if .Values.networking.tailnet.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "42"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: {{ .Values.secrets.provider }}
    kind: ClusterSecretStore
  target:
    name: operator-oauth
  refreshPolicy: Periodic
  refreshInterval: 2h
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.networking.tailnet.credentials.clientId.remoteRef }}
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.networking.tailnet.credentials.clientSecret.remoteRef }}
{{- end -}}