  # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/fluxcd.controlplane.io/fluxinstance_v1.json
  apiVersion: fluxcd.controlplane.io/v1
  kind: FluxInstance
  metadata:
    name: flux
    namespace: flux-system
    annotations:
      fluxcd.controlplane.io/reconcile: "enabled"
      fluxcd.controlplane.io/reconcileEvery: "5m"
      fluxcd.controlplane.io/reconcileTimeout: "2m"
  spec:
    distribution:
      registry: "ghcr.io/fluxcd"
      version: "2.8.x"
    migrateResources: true
    wait: true
    cluster:
      type: aws
    storage:
      class: standard
      size: "4Gi"
    kustomize:
      patches:
        - target:
            kind: Deployment
          patch: |
            - op: add
              path: /spec/template/spec/nodeSelector
              value:
                niovial.io/node-purpose: system
            - op: add
              path: /spec/template/spec/tolerations
              value:
                - key: "CriticalAddonsOnly"
                  operator: "Exists"
    sync:
      interval: 1m
      kind: GitRepository
      path: k8s/cluster
      ref: refs/heads/main
      url: https://github.com/rtnkwami/portfolio-hub
      name: portfolio-hub