apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vlogs-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: victoria-logs-collector
    repoURL: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-collector
    targetRevision: 0.3.6
    helm:
      valuesObject:
        remoteWrite:
          - url: http://vlogs-victoria-logs-single-server.observability.svc.cluster.local:9428
        podMonitor:
          enabled: true
        tolerations:
          - operator: Exists
  destination:
    namespace: vlogs-collector
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true