apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-dns-secret.yaml
  - cluster-gateway.yaml
  - cluster-secret-store.yaml
  - cluster-issuer.yaml
  - tailscale-gateway.yaml
  - tailnet-argocd.yaml
  - tailnet-grafana.yaml
