apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: tailscale-gateway-config
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  service:
    type: LoadBalancer
    loadBalancerClass: tailscale
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: tailscale-gateway-config
    namespace: gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: management-gateway
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  gatewayClassName: tailscale
  infrastructure:
    annotations:
      tailscale.com/hostname: management-gateway
  listeners:
    - name: https
      hostname: "*.internal.niovial.io"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: internal-niovial-io-tls