{{- range $component, $config := pick .Values.app "frontend" "backend" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "..fullname" $) $component }}
  labels:
    {{- include "..labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "..selectorLabels" $ | nindent 6 }}
      {{- with $config.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "..labels" $ | nindent 8 }}
        {{- with $config.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $config.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $component }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $config.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $config.service.containerPort }}
              protocol: TCP
          {{- with index $.Values.secrets $component }}
          envFrom:
            {{- range $group, $secrets := . }}
              - secretRef:
                  name: {{ printf "%s-%s-%s" (include "..fullname" $) $component $group }}
            {{- end }}
          {{- end }}
          {{- with $config.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $.Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
