apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: zitadel-db-password
  namespace: zitadel
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  length: 32
  symbols: 0
  digits: 10
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-db-credentials
  namespace: zitadel
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "2h"
  target:
    # cnpg already creates a secret which we can auto-update
    name: zitadel-db-app
    creationPolicy: Merge
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        pgpass: "zitadel-db-rw:5432:app:app:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://zitadel-db-rw.zitadel:5432/app?password={{ .password }}&user=app"
        uri: "postgresql://app:{{ .password }}@zitadel-db-rw.zitadel:5432/app?sslmode=require"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: zitadel-db-password
