apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-credentials
            key: clientId
            namespace: external-secrets
          clientSecret:
            name: infisical-credentials
            key: clientSecret
            namespace: external-secrets
      secretsScope:
        projectSlug: homelab-43la
        environmentSlug: staging