apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-cloudflare-token
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  data:
    - secretKey: token
      remoteRef:
        key: k8s-externaldns-token
