apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: cert-manager
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    targetRevision: 1.20.2
    helm:
      valuesObject:
        global:
          nodeSelector:
            niovial.io/node-purpose: system
        tolerations:
          - key: niovial.io/node-purpose
            operator: Exists
        replicaCount: 2
        podDisruptionBudget:
          enabled: true
        crds:
          enabled: true
        config:
          enableGatewayAPI: true
        topologySpreadConstraints:
          - topologyKey: "topology.kubernetes.io/zone"
            maxSkew: 1
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: cert-manager
                app.kubernetes.io/instance: cert-manager
            matchLabelKeys: ["pod-template-hash"]
        webhook:
          replicaCount: 2
          podDisruptionBudget:
            enabled: true
          tolerations:
            - key: niovial.io/node-purpose
              operator: Exists
          topologySpreadConstraints:
            - topologyKey: "topology.kubernetes.io/zone"
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: webhook
                  app.kubernetes.io/instance: cert-manager
              matchLabelKeys: ["pod-template-hash"]
        cainjector:
          replicaCount: 2
          podDisruptionBudget:
            enabled: true
          tolerations:
            - key: niovial.io/node-purpose
              operator: Exists
          topologySpreadConstraints:
            - topologyKey: "topology.kubernetes.io/zone"
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: cainjector
                  app.kubernetes.io/instance: cert-manager
              matchLabelKeys: ["pod-template-hash"]
        startupapicheck:
          tolerations:
            - key: niovial.io/node-purpose
              operator: Exists
        prometheus:
          servicemonitor:
            enabled: true
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
