apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: infrastructure
  source:
    chart: prometheus-node-exporter
    repoURL: oci://ghcr.io/prometheus-community/charts/prometheus-node-exporter
    targetRevision: 4.55.0
    helm:
      valuesObject:
        extraArgs:
          - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
          - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
        prometheus:
          monitor:
            enabled: true 
  destination:
    namespace: node-exporter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true