apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.7.0
    helm:
      valuesObject:
        global:
          nodeSelector:
            niovial.io/node-purpose: system
          tolerations:
            - key: niovial.io/node-purpose
              operator: Equal
              value: system
          topologySpreadConstraints:
            - topologyKey: "topology.kubernetes.io/zone"
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: external-secrets
              matchLabelKeys: ["pod-template-hash"]
        replicaCount: 2
        podDisruptionBudget:
          enabled: true
        webhook:
          replicaCount: 2
          podDisruptionBudget:
            enabled: true
        certController:
          replicaCount: 2
          podDisruptionBudget:
            enabled: true
        serviceMonitor:
          enabled: true
        grafanaDashboard:
          enabled: true
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true