apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.21.1
    helm:
      valuesObject:
        nodeSelector:
          niovial.io/node-purpose: system
        tolerations:
          - key: niovial.io/node-purpose
            operator: Equal
            value: system
        sources:
          - service
          - gateway-httproute
          - gateway-tlsroute
          - gateway-tcproute
        rbac:
          additionalPermissions:
            - apiGroups: [""]
              resources: ["namespaces"]
              verbs: ["get","watch","list"]
        provider:
          name: cloudflare
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
              # see configuration/cloudflare-dns-secret
              name: cloudflare-dns-token
              key: token
        txtOwnerId: homelab
        serviceMonitor:
          enabled: true
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
