apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.20.1
    helm:
    valuesObject:
      nodeSelector:
        niovial.io/node-purpose: system
      tolerations:
        - key: niovial.io/node-purpose
          operator: Equal
          value: system
      topologySpreadConstraints:
        operator:
          - topologyKey: "topology.kubernetes.io/zone"
            maxSkew: 1
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: keda
            matchLabelKeys: ["pod-template-hash"]
        metricsServer:
          - topologyKey: "topology.kubernetes.io/zone"
            maxSkew: 1
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: keda
            matchLabelKeys: ["pod-template-hash"]
        webhooks:
          - topologyKey: "topology.kubernetes.io/zone"
            maxSkew: 1
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: keda
            matchLabelKeys: ["pod-template-hash"]
      operator:
        replicaCount: 2
      metricsServer:
        replicaCount: 2
      webhooks:
        replicaCount: 2
      prometheus:
        metricServer:
          enabled: true
          serviceMonitor:
            enabled: true
        operator:
          enabled: true
          serviceMonitor:
            enabled: true
        webhooks:
          enabled: true
          serviceMonitor:
            enabled: true
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true