apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: infrastructure
  source:
    chart: cloudnative-pg
    repoURL: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
    targetRevision: 0.29.0
    helm:
      valuesObject:
        nodeSelector:
          niovial.io/node-purpose: system
        tolerations:
          - key: niovial.io/node-purpose
            operator: Equal
            value: system
        replicaCount: 2
        topologySpreadConstraints:
          - topologyKey: "topology.kubernetes.io/zone"
            maxSkew: 1
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: cloudnative-pg
            matchLabelKeys: ["pod-template-hash"]
        monitoring:
          podMonitorEnabled: true
          grafanaDashboard:
            create: true
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
