apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    chart: zitadel
    repoURL: https://charts.zitadel.com
    targetRevision: "10.0.4"
    helm:
      valuesObject:
        replicaCount: 3
        metrics:
          serviceMonitor:
            enabled: true
        pdb:
          enabled: true
          maxUnavailable: 1
        env:
          - name: ZITADEL_DATABASE_POSTGRES_DSN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.database.name }}-app
                key: uri
        gateway:
          httpRoute:
            enabled: true
            parentRefs:
              - name: external-gateway
                namespace: gateway-system
            hostnames:
              - {{ .Values.app.domain }}
        zitadel:
          masterkeySecretName: zitadel-master-key
          configmapConfig:
            ExternalDomain: {{ .Values.app.domain }}
          dbSslCaCrtSecret: {{ .Values.database.name }}-ca
        initJob:
          command: "zitadel"
        login:
          gateway:
            httpRoute:
              enabled: true
              parentRefs:
                - name: external-gateway
                  namespace: gateway-system
              hostnames:
                - {{ .Values.app.domain }}
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true