{{- if not .Values.backups.store.isS3 }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-backup-keys
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: {{ .Values.secrets.provider }}
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "2h"
  target:
    deletionPolicy: Delete
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.secrets.backupKeys.accessKeyId }}
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: {{ .Values.secrets.backupKeys.accessSecretKey }}
{{- end }}
  