apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: zitadel-daily-backups
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schedule: {{ .Values.backups.schedule }}
  backupOwnerReference: self
  cluster:
    name: {{ .Values.database.name }}
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  target: prefer-standby