apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshInterval: "1h0m0s"
  data:
    # key within the secret that ESO creates in the cluster
    - secretKey: dns-token
      # name of the secret created within the cluster secret store
      remoteRef:
        key: cloudflare-dns-token
