apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: portfolio-hub
  path: "./k8s/cluster/infra/node-scaling/karpenter"
  prune: true
  timeout: 1m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: karpenter
      namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-nodepools
  namespace: flux-system
spec:
  dependsOn:
    - name: karpenter
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: portfolio-hub
  path: "./k8s/cluster/infra/node-scaling/nodepools"
  prune: true
  timeout: 1m