apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # wave 1:
  - addons/envoy-gateway-crds.yaml
  - addons/vlogs-collector.yaml
  - addons/node-exporter.yaml
  # wave 2:
  - addons/cert-manager.yaml
  - addons/cloudnative-pg.yaml
  - addons/envoy-gateway.yaml # (depends on: envoy-gateway-crds)
  - addons/external-secrets.yaml
  - addons/keda.yaml
  # wave 3:
  - addons/barman-cloud.yaml # (depends on: cloudnative-pg)
  - addons/vm-operator.yaml # (depends on: cert-manager)
  - configuration/networking/dns-tls/cluster-secret-store.yaml
  # wave 4:
  - addons/victoria-metrics-stack.yaml # (depends on: vm-operator)
  - addons/victoria-logs.yaml # (depends on: vm-operator)
  - configuration/networking/dns-tls/certmanager-secret.yaml # (depends on: cluster-secret-store)
  - configuration/networking/dns-tls/externaldns-secret.yaml # (depends on: cluster-secret-store)
  # wave 5:
  - addons/external-dns.yaml # (depends on: externaldns-secret)
  - configuration/networking/dns-tls/cluster-issuer.yaml
  # wave 6-8:
  - configuration/networking/gateways/cluster-gateway.yaml
  - configuration/networking/gateways/tailscale-gateway.yaml
  # wave 9:
  - configuration/tailnet-argocd.yaml
  - configuration/tailnet-grafana.yaml
