apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: management-gateway-proxy
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet:
        pod:
          tolerations:
            - key: niovial.io/node-purpose
              operator: Equal
              value: system
      envoyService:
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: management-gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: management-gateway-proxy
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: management-gateway
  namespace: gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  gatewayClassName: tailscale
  listeners:
    - name: https
      hostname: "*.internal.niovial.io"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: internal-niovial-io-tls