{{- if eq .Values.secrets.provider "infisical" -}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
  annotations:
    argocd.argoproj.io/sync-wave: "32"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    infisical:
    {{- toYaml .Values.secrets.config.infisical | nindent 6 }}
{{- end -}}