{{- if .Values.networking.tailnet.enabled -}}
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailnet-service-proxies
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  {{- if eq .Values.networking.tls.issuer.environment "staging" }}
  useLetsEncryptStagingEnvironment: true
  {{- end }}
  statefulSet:
    pod:
      {{- if .Values.controllers.nodePlacement.enabled }}
      {{- with .Values.controllers.nodePlacement.nodeSelector }}
      {{- include "controller.nodeSelector" $ | nindent 6 }}
      {{- end }}
      {{- with .Values.controllers.nodePlacement.tolerations }}
      {{- include "controller.tolerations" $ | nindent 6 }}
      {{- end }}
      {{- end  }}
      topologySpreadConstraints:
        - topologyKey: "topology.kubernetes.io/zone"
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              tailscale.com/parent-resource: service-proxies
          matchLabelKeys: ["controller-revision-hash"]
  metrics:
    enable: true
    serviceMonitor:
      enable: true
{{- end  }}