apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ printf "%s-%s" (include "..fullname" .) "database" }}
spec:
  imageName: {{ .Values.database.config.image.repository }}:{{ .Values.database.config.image.tag }}
  instances: {{ .Values.database.config.instances }}
  storage:
    size: {{ .Values.database.config.storageSize }}
    {{- with .Values.database.config.storageClass }}
    storageClass: {{ . }}
    {{- end }}
  walStorage:
    size: {{ .Values.database.config.walStorageSize }}
  postgresql:
    synchronous:
      method: any
      number: {{ .Values.database.config.syncReplicas }}
      dataDurability: required
  affinity:
    enablePodAntiAffinity: true
    topologyKey: topology.kubernetes.io/zone
    podAntiAffinityType: required
    {{- with .Values.database.config.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end -}}
    {{- with .Values.database.config.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
---
{{- if .Values.database.config.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ printf "%s-%s" (include "..fullname" .) "database" }}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ printf "%s-%s" (include "..fullname" .) "database" }}
  podMetricsEndpoints:
  - port: metrics
{{- end }}