apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-master-key
  namespace: zitadel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  data:
    - secretKey: masterkey
      remoteRef:
        key: k8s-zitadel-master-key
