apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 2h
  type: "oci"
  url: oci://quay.io/jetstack/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  # interval at which HelmRelease config is reconciled
  interval: 1m
  targetNamespace: cert-manager
  # cert-manager's helm chart manages its own crds, and so no need for
  # install.crds or upgrade.crds
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  chart:
    spec:
      chart: cert-manager
      version: 1.20.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      # interval at which chart source is reconciled
      interval: 2h
  values:
    global:
      nodeSelector:
        niovial.io/node-purpose: system
    # cert-manager handles it's own crds
    crds:
      enabled: true
    config:
      enableGatewayAPI: true
    webhook:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
    cainjector:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
    startupapicheck:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists