apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 2h
  type: "oci"
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  # interval at which HelmRelease config is reconciled
  interval: 10m
  targetNamespace: cnpg-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.28.3
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      # interval at which chart source is reconciled
      interval: 2h
  values:
    nodeSelector:
      niovial.io/node-purpose: system
    tolerations:
      - key: niovial.io/node-purpose
        operator: Equal
        value: system
        effect: NoSchedule
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true