apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 2h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  # interval at which HelmRelease config is reconciled
  interval: 1m
  targetNamespace: external-secrets
  # external-secrets' helm chart manages its own crds, and so no need for
  # install.crds or upgrade.crds
  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true
  chart:
    spec:
      chart: external-secrets
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      # interval at which chart source is reconciled
      interval: 2h
  values:
    global:
      nodeSelector:
        niovial.io/node-purpose: system
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists