apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-repo
  namespace: flux-system
spec:
  interval: 2h
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.5.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 2h
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: gateway-api-repo
  path: "./config/crd/experimental"
  prune: true
  timeout: 1m