apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 2h
  type: "oci"
  url: oci://public.ecr.aws/karpenter/karpenter
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  # interval at which HelmRelease config is reconciled
  interval: 10m
  targetNamespace: kube-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
  chart:
    spec:
      chart: karpenter
      version: 1.13.0
      sourceRef:
        kind: OCIRepository
        name: karpenter
        namespace: flux-system
      # interval at which chart source is reconciled
      interval: 2h
  values:
    nodeSelector:
      niovial.io/node-purpose: system