apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: infrastructure
  source:
    chart: gateway-helm
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    targetRevision: v1.8.2
    helm:
      valuesObject:
        crds:
          enabled: false
        deployment:
          replicas: 2
          pod:
            {{- if .Values.controllers.nodePlacement.enabled }}
            {{- include "controller.nodeSelector" . | nindent 12 -}}
            {{- include "controller.tolerations" . | nindent 12 }}
            {{- end }}
            topologySpreadConstraints:
              - topologyKey: "topology.kubernetes.io/zone"
                maxSkew: 1
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: envoy-gateway
                matchLabelKeys: ["pod-template-hash"]
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
