apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: infrastructure
  source:
    chart: gateway-crds-helm
    repoURL: oci://docker.io/envoyproxy/gateway-crds-helm
    targetRevision: v1.8.2
    helm:
      valuesObject:
        crds:
          gatewayAPI:
            enabled: {{ .Values.networking.gatewayAPI.enabled }}
          envoyGateway:
            enabled: true
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true