apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: spegel
    repoURL: oci://ghcr.io/spegel-org/helm-charts/spegel
    targetRevision: 0.7.3
    helm:
      valuesObject:
        spegel:
          containerdRegistryConfigPath: /etc/cri/conf.d/hosts
        serviceMonitor:
          enabled: true
        grafanaDashboard:
          enabled: true
  destination:
    namespace: spegel
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true