apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: infrastructure
  source:
    chart: victoria-metrics-k8s-stack
    repoURL: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
    targetRevision: 0.86.0
    helm:
      valuesObject:
        prometheus-node-exporter:
          enabled: false
        defaultDatasources:
          extra:
            - name: VictoriaLogs
              type: victoriametrics-logs-datasource
              url: http://vlogs-victoria-logs-single-server:9428
        victoria-metrics-operator:
          enabled: false
        grafana:
          plugins:
            - victoriametrics-logs-datasource
        vmsingle:
          spec:
            removePvcAfterDelete: true
            resources:
              requests:
                storage: {{ .Values.monitoring.storage.size.metrics }}
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data/admin-password
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true